stages:
  - build
  - test

build_job:
  stage: build
  script:
    - cd TourGuide/
    - ./gradlew bootJar
  image: gradle:7-jdk17-alpine
  artifacts:
    paths:
      - TourGuide/build/libs/*.jar

unitTest_job:
  stage: test
  script:
    - cd TourGuide/
    - ./gradlew test
  image: gradle:7-jdk17-alpine
  artifacts:
    paths:
      - TourGuide/build/reports/jacoco/test/jacocoTestReport.xml
      - TourGuide/build/jacocoUTHtml/

integrationTest_job:
  stage: test
  script:
    - cd TourGuide/
    - ./gradlew integrationTest
  image: gradle:7-jdk17-alpine
  artifacts:
    paths:
      - TourGuide/build/reports/jacoco/jacocoIntegrationTestReport/jacocoIntegrationTestReport.xml
