stages:
  - build
  - test
  - -visualize

build_job:
  stage: build
  script:
    - cd TourGuide/
    - ./gradlew bootJar
  image: openjdk:17-alpine
  artifacts:
    paths:
      - build/libs/tourGuide-1.0.0.jar


unitTest_job:
  stage: test
  script:
    - cd TourGuide/
    - ./gradlew test
  image: openjdk:17-alpine
  artifacts:
    paths:
      - build/reports/jacoco/test/jacocoTestReport.xml

integrationTest_job:
  stage: test
  script:
    - cd TourGuide/
    - ./gradlew integrationTest
  image: openjdk:17-
  artifacts:
    paths:
      - build/reports/jacoco/jacocoIntegrationTestReport/jacocoIntegrationTestReport.xml

coverage-unitTest:
  stage: visualize
  image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.7
  script:
    # convert report from jacoco to cobertura, using relative project path
    - python /opt/cover2cover.py target/site/jacoco/jacoco.xml $CI_PROJECT_DIR/src/main/java/ > target/site/cobertura.xml
  needs: ["unitTest_job"]
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: target/site/cobertura.xml
