version: '3'
services:
  location-service:
    image: tourguide/locationservice
    container_name: location-service
    ports:
      - 8081:8081
    networks:
      - spring-cloud-network
  reward-service:
    image: tourguide/rewardservice
    container_name: reward-service
    ports:
      - 8083:8083
    networks:
      - spring-cloud-network
  user-service:
    image: tourguide/userservice
    container_name: user-service
    ports:
      - 8082:8082
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge
